### ISSUE TITLE
대화방

### ISSUE THREAD

**Issue by terrykwon** [terrykwon/BankShare#1]
[https://xd.adobe.com/view/cca349d2-b6ce-4b2d-b570-01fb8cfcee21/](https://xd.adobe.com/view/cca349d2-b6ce-4b2d-b570-01fb8cfcee21/)

**Comment by hehpollon** [comment]
여기가 대화방인가요?

**Comment by terrykwon** [comment]
>네
>>네
>>>네
>>>>네

**Comment by terrykwon** [comment]
커밋은 그냥 마스터에 해도 될거 같은데, 그러면 동시에 똑같은걸 작업하고 있으면 안되겠네요

**Comment by terrykwon** [comment]
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [ ] 6
- [ ] 7
- [x] 8
- [ ] 9
- [ ] 10
- [ ] 11

> 위에 XD 링크 기준 4번까지 만들었네요~
